var lang = {
    en: {
        home: "Home",
        movies:  "Movies",
        tvShows: "TV Shows",
        liveTv: "Live TV",
        subscriptions: "Subcriptions",
        joinPrime: "Join Prime",
        welcomeToPrime: "Welcome to Prime Video",
        joinPrimeMessage: "Join Prime to watch the latest movies, TV shows and award-winning Amazon Originals",
        signInbtn: "Sign in to join Prime",
        movieRentalsMessage: "Movie rentals on Prime Video",
        earlyAccess: "Early Access to new movies, before digital subscription",
        rentNow: "Rent now",
        favSubscriptionTitleMessage: "Your favorite subscriptions all in one place",
        favSubscriptionSubTitleMessage: "  With Prime Video Channels, find shows and movies from your favorite channels all in one place. Enjoy with an add-on subscription to Channels of your choice",
        termsPrivacyText: "Terms & Privacy Notice",
        feedbackText: "Send us feedback",
        helpText: "Help",
        affiliateText: "© 1996-2025, Amazon.com, Inc. or its affiliates"
    },
    hindi:{
        home: "घर",
        movies:  "चलचित्र",
        tvShows: "टीवी शो",
        liveTv: "लाइव टीवी",
        subscriptions: "सदस्यता",
        joinPrime: "प्राइम से जुड़ें",
        welcomeToPrime: "प्राइम वीडियो में आपका स्वागत है",
        joinPrimeMessage: "नवीनतम फिल्में, टीवी शो और पुरस्कार विजेता अमेज़ॅन ओरिजिनल देखने के लिए प्राइम से जुड़ें",
        signInbtn: "प्राइम से जुड़ने के लिए साइन इन करें",
        movieRentalsMessage: "प्राइम वीडियो पर मूवी रेंटल",
        earlyAccess: "डिजिटल सदस्यता से पहले, नई फिल्मों तक शीघ्र पहुंच",
        rentNow: "अभी किराए पर लें",
        favSubscriptionTitleMessage: "आपकी सभी पसंदीदा सदस्यताएँ एक ही स्थान पर",
        favSubscriptionSubTitleMessage: "प्राइम वीडियो चैनलों के साथ, अपने पसंदीदा चैनलों के शो और फिल्में एक ही स्थान पर ढूंढें। अपनी पसंद के चैनलों की ऐड-ऑन सदस्यता के साथ आनंद लें",
        termsPrivacyText: "शर्तें एवं गोपनीयता सूचना",
        feedbackText: "हमें फीडबैक भेजें",
        helpText: "मदद",
        affiliateText: "© 1996-2025, Amazon.com, Inc. या इसके सहयोगी"
    },
    spanish:{
        home: "Home",
        movies:  "Movies",
        tvShows: "TV Shows",
        liveTv: "Live TV",
        subscriptions: "Subcriptions",
        joinPrime: "Join Prime",
        welcomeToPrime: "Welcome to Prime Video",
        joinPrimeMessage: "Join Prime to watch the latest movies, TV shows and award-winning Amazon Originals",
        signInbtn: "Sign in to join Prime",
        movieRentalsMessage: "Movie rentals on Prime Video",
        earlyAccess: "Early Access to new movies, before digital subscription",
        rentNow: "Rent now",
        favSubscriptionTitleMessage: "Your favorite subscriptions all in one place",
        favSubscriptionSubTitleMessage: "  With Prime Video Channels, find shows and movies from your favorite channels all in one place. Enjoy with an add-on subscription to Channels of your choice",
        termsPrivacyText: "Terms & Privacy Notice",
        feedbackText: "Send us feedback",
        helpText: "Help",
        affiliateText: "© 1996-2025, Amazon.com, Inc. or its affiliates"
    }
}

export default lang;