var lang = {
    en: {
        home: "Home",
        movies:  "Movies",
        tvShows: "TV Shows",
        liveTv: "Live TV",
        subscriptions: "Subcriptions",
        joinPrime: "Join Prime",
        welcomeToPrime: "Welcome to Prime Video",
        joinPrimeMessage: "Join Prime to watch the latest movies, TV shows and award-winning Amazon Originals",
        signInbtn: "Sign in to join Prime",
        movieRentalsMessage: "Movie rentals on Prime Video",
        earlyAccess: "Early Access to new movies, before digital subscription",
        rentNow: "Rent now",
        favSubscriptionTitleMessage: "Your favorite subscriptions all in one place",
        favSubscriptionSubTitleMessage: "  With Prime Video Channels, find shows and movies from your favorite channels all in one place. Enjoy with an add-on subscription to Channels of your choice",
        termsPrivacyText: "Terms & Privacy Notice",
        feedbackText: "Send us feedback",
        helpText: "Help",
        affiliateText: "© 1996-2025, Amazon.com, Inc. or its affiliates",
        signIn: "Sign In",
        emailId: "Email Id",
        password: "Password",
        continue: "Continue",
        aggrementText: "By continuing, you agree to the Amazon",
        aggrementCondition: "Conditions of Use and Privacy Notice",
        signUp: "Sign Up",
        name: "Name",
        newToAmazon: "New to Amazon?",
        popularMovies: "Popular Movies",
        nowPlayingMovies: "Now Playing Movies",
        topRatedMovies: "Top Rated Movies",
        upcomingMovies: "Upcoming Movies",
        chatWithUs: "Chat with Us",
        play: "Play",
        info: "Info",
        profile: "Profile",
        settings: "Settings",
        logOut: "Log Out",
        gptHintText: "What would you like to watch..."
    },
    hindi:{
        home: "घर",
        movies:  "चलचित्र",
        tvShows: "टीवी शो",
        liveTv: "लाइव टीवी",
        subscriptions: "सदस्यता",
        joinPrime: "प्राइम से जुड़ें",
        welcomeToPrime: "प्राइम वीडियो में आपका स्वागत है",
        joinPrimeMessage: "नवीनतम फिल्में, टीवी शो और पुरस्कार विजेता अमेज़ॅन ओरिजिनल देखने के लिए प्राइम से जुड़ें",
        signInbtn: "साइन इन करें",
        movieRentalsMessage: "प्राइम वीडियो पर मूवी रेंटल",
        earlyAccess: "डिजिटल सदस्यता से पहले, नई फिल्मों तक शीघ्र पहुंच",
        rentNow: "अभी किराए पर लें",
        favSubscriptionTitleMessage: "आपकी सभी पसंदीदा सदस्यताएँ एक ही स्थान पर",
        favSubscriptionSubTitleMessage: "प्राइम वीडियो चैनलों के साथ, अपने पसंदीदा चैनलों के शो और फिल्में एक ही स्थान पर ढूंढें। अपनी पसंद के चैनलों की ऐड-ऑन सदस्यता के साथ आनंद लें",
        termsPrivacyText: "शर्तें एवं गोपनीयता सूचना",
        feedbackText: "हमें फीडबैक भेजें",
        helpText: "मदद",
        affiliateText: "© 1996-2025, Amazon.com, Inc. या इसके सहयोगी",
        signIn: "दाखिल करना",
        emailId: "ईमेल आईडी",
        password: "पासवर्ड",
        continue: "जारी रखना",
        aggrementText: "जारी रखकर, आप अमेज़न से सहमत हैं",
        aggrementCondition: "उपयोग की शर्तें और गोपनीयता सूचना",
        signUp: "साइन अप करें",
        name: "नाम",
        newToAmazon: "अमेज़न पर नए हैं?",
        popularMovies: "लोकप्रिय फ़िल्में",
        nowPlayingMovies: "अभी फ़िल्में चल रही हैं",
        topRatedMovies: "शीर्ष रेटेड फिल्में",
        upcomingMovies: "आने वाली फिल्में",
        chatWithUs: "हमारे साथ चैट करें",
        play: "खेल",
        info: "विवरण",
        profile: "प्रोफ़ाइल",
        settings: "सेटिंग्स",
        logOut: "लॉग आउट",
        gptHintText: "आप क्या देखना पसंद करेंगे..."
    },
    spanish:{
        home: "Hogar",
        movies:  "Cine",
        tvShows: "Programas de televisión",
        liveTv: "Televisión en vivo",
        subscriptions: "Suscripciones",
        joinPrime: "Únete a Prime",
        welcomeToPrime: "Bienvenido a Prime Video",
        joinPrimeMessage: "Únase a Prime para ver las últimas películas, programas de televisión y originales de Amazon galardonados",
        signInbtn: "Únete a Prime",
        movieRentalsMessage: "Alquiler de películas en Prime Video",
        earlyAccess: "Acceso anticipado a nuevas películas, antes de la suscripción digital",
        rentNow: "Alquila ahora",
        favSubscriptionTitleMessage: "Tus suscripciones favoritas, todas en un solo lugar",
        favSubscriptionSubTitleMessage: "Con Prime Video Channels, encuentra programas y películas de tus canales favoritos, todo en un solo lugar. Disfruta con una suscripción adicional a los canales de tu elección",
        termsPrivacyText: "Términos y aviso de privacidad",
        feedbackText: "Envíanos tus comentarios",
        helpText: "Ayuda",
        affiliateText: "© 1996-2025, Amazon.com, Inc. o sus afiliados",
        signIn: "Iniciar sesión",
        emailId: "ID de correo electrónico",
        password: "Contraseña",
        continue: "Continuar",
        aggrementText: "Al continuar, aceptas el Amazon",
        aggrementCondition: "Condiciones de Uso y Aviso de Privacidad",
        signUp: "Inscribirse",
        name: "Nombre",
        newToAmazon: "¿Nuevo en Amazon?",
        popularMovies: "Películas populares",
        nowPlayingMovies: "Ahora reproduciendo películas",
        topRatedMovies: "Películas mejor valoradas",
        upcomingMovies: "Próximas películas",
        chatWithUs: "Chatea con nosotros",
        play: "Jugar",
        info: "detalles",
        profile: "Perfil",
        settings: "Ajustes",
        logOut: "Finalizar la sesión",
        gptHintText: "¿Qué te gustaría ver...?"
    }
}

export default lang;